### PR TITLE
Glossary

### PR DESCRIPTION
**Pull request by KaraAJC**
Here, I've created an index and a set of terms with links to direct sources, or articles that are more suited to go into detail about the term.

### CODE REVIEW

**Comment by KaraAJC** [comment]
PR is up for issue #20

**Review by sublimemarch — APPROVED** [review]
This looks great to me! I really like the way you created an index for the glossary, too.

**Review by cmho — APPROVED** [review]
looks good! 🌟

**Comment by sublimemarch** [comment]
Awesome! Two approved reviewers means we're good to merge, doing that now. 🌷

**Comment by KaraAJC** [comment]
bitmoji

**Pull request merged**
