### PR TITLE
Change wording in contributing guidelines to be more clear.

### PR DESCRIPTION
**Pull request by thejessleigh**
Addresses #56

### CODE REVIEW

**Comment by thejessleigh** [comment]
Also requesting a review from @AdiraSlat who opened the issue.

**Review by cmho — APPROVED** [review]
👍

**Comment by sublimemarch** [comment]
Everyone in favor of just merging this? @cmho @thejessleigh

**Comment by thejessleigh** [comment]
I'm good merging this in whenever.

**Pull request merged**
