### PR TITLE
39 emotional labor

### PR DESCRIPTION
**Pull request by thejessleigh**
Separate out categories for accuracy and future expansion.

### CODE REVIEW

**Review by sublimemarch — COMMENTED** [review]
I think we should include a link to the definition of The Second Shift, either to its definition in our glossary or elsewhere.

http://geekfeminism.wikia.com/wiki/Second_shift

**Comment by thejessleigh** [comment]
Hmmmmm.....just looked at our glossary definition of Emotional Labor:

```
Emotional Labor: Tasks that require a high degree of understanding or management of emotions. The tasks are also commonly "extra" or undervalued for the amount of actual labor or time spent on them, and left out of official job descriptions or task assignments even when the function is vital to the organization (sometimes known as the Second Shift).
```

I think I'm going to edit this to be more accurate while I'm digging in on emotional labor stuff.

**Comment by thejessleigh** [comment]
Okay, I think this should do it. Let me know if you think I missed anything else.

**Review by cmho — APPROVED** [review]
looks good! ⭐️

**Comment by sublimemarch** [comment]
Great job! 🌹

**Pull request merged**
